ARRAY OPERATIONS

In [5]:
import numpy as np
arr=np.arange(1,11)
print(arr[-9])
print(arr[2])
print(arr[2:8])

2
3
[3 4 5 6 7 8]


In [25]:
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[1])
print(arr[2])
print(arr[2,1])
print(arr[:,2])

[4 5 6]
[7 8 9]
8
[3 6 9]


In [18]:
arr=np.array([3,5,1,3,98,67,56,4,3,0,1])
print(np.sort(arr))
arr1=np.array([[10,9],
              [6,5],
              [8,7]])
print(np.sort(arr1,axis=0))
print(np.sort(arr1,axis=1))

[ 0  1  1  3  3  3  4  5 56 67 98]
[[ 6  5]
 [ 8  7]
 [10  9]]
[[ 9 10]
 [ 5  6]
 [ 7  8]]


In [ ]:
arr=np.array([3,5,1,3,98,67,56,4,3,0,1])
print(np.sort(arr[arr>5]))
print(np.sort(arr[arr%2==0]))
print(arr[arr==0])
# CONCEPT OF MASK
mask=arr<20
print(arr[mask])

[56 67 98]
[ 0  4 56 98]
[0]
[3 5 1 3 4 3 0 1]


np.where

In [27]:
arr=np.array([3,5,1,3,98,67,56,4,3,0,1])
print(arr[np.where(arr<6)])    ## GIVES INDEX NUMBER OF ALL WHO SATISFY THE CONDITION
print(np.where(arr>2,arr*5,arr*0))
print(np.where(arr>5,arr,False))

[3 5 1 3 4 3 0 1]
[ 15  25   0  15 490 335 280  20  15   0   0]
[ 0  0  0  0 98 67 56  0  0  0  0]


ADDING AND REMOVING DATA

In [31]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
print(np.concatenate((arr,arr2)))


[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


ARRAY COMPATIBILITY

In [8]:
import numpy as np
print(arr.shape==arr2.shape)

True


VSTACK AND HSTACK
# VSTACK IS SIMILAR TO np.concatenate((arr,arr2), axis=0)    BOTH DO THE SAME WORK
# HSTACK IS SIMILAR TO np.concatenate((arr,arr2), axis=1)    Both do the same work
# CONCATENATE CAN DO BOTH OF THEIR WORK HENCE ITS MORE FLEXIBLE

In [ ]:
print(np.vstack((arr,arr2)))
print(np.concatenate((arr,arr2), axis=0))
# same output

print(np.hstack((arr,arr2)))
print(np.concatenate((arr,arr2),axis=1))
#same output

print(arr)
#orignal array remains unchanged

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]


DELETION IN ARRAY(1D AND 2D)

# DELETE FLATTENS THE ARRAY AND THEN DELETES THE GIVEN INDEX
# WE CAN USE np.delete(arr,2, axis=0)  to delete third row
# and np.delete(arr,2,axis=1) to delete third coloumn
# WE CAN'T DELETE A SINGLE ELEMENT AS IT WILL DISTURB THE HOMOGENITY OF OUR 2DARRAY

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(np.delete(arr1,2))      # DOESN'T GIVE DELETED ELEMENT INSTEAD GIVES NEW ARR

print(arr1)


## FOR 2D

arr_2d=np.array([[1,2,3],      
              [4,5,6]])
print(np.delete(arr_2d,1))
print(np.delete(arr_2d,0, axis=0))    #DELETES ROW
print(np.delete(arr,(0,1), axis=0))

print(np.delete(arr,2,axis=1))        #DELETES COLUMN

[1 2]
[1 2 3]
[1 3 4 5 6]
[[4 5 6]]
[]
[[1 2]
 [4 5]]
