In [2]:

import numpy as np
temp=[1,2,3,4]
array=np.array([1,2,3,4])
print(temp)
print(array)

[1, 2, 3, 4]
[1 2 3 4]


## numpy array takes less time to execute than python list(shown below)

In [1]:
import numpy as np
import time
start=time.time()
py_list=[i*2 for i in range(1000000)] 
print("Time:", time.time()-start)
start=time.time()
arr=np.arange(1000000)*2
print("Time: ", time.time()-start)


Time: 0.10082411766052246
Time:  0.005010128021240234


Random function

In [1]:
import numpy as np
arr=np.arange(1000,1005,4)
print(arr)
arr1=np.random.randint(0,10,(2,3))
print(arr1)


[1000 1004]
[[2 1 6]
 [6 5 2]]


#ARRAY PROPERTIES

In [13]:
import numpy as np
arr=np.array([[1,2,3,0],
              ["4",5,6,0.0],
              ['7',8,9,10]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)


(3, 4)
2
<U32
12


In [17]:
import numpy as np
arr=np.array([np.arange(1,10),
              np.arange(6,15)])
print(arr)

[[ 1  2  3  4  5  6  7  8  9]
 [ 6  7  8  9 10 11 12 13 14]]


---> ARRAY RESHAPING

In [25]:
import numpy as np
arr=np.arange(1,11)
print(arr)
reshaped=arr.reshape(2,5)
print(reshaped)
print(reshaped.ravel())
print(reshaped.T)




[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
